config: gitignore + Add remote backend and variable definitions
gitignore


test


There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported block type

  on main.tf line 73:
  73: backend "s3" {

Blocks of type "backend" are not expected here.
ignore